export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
}

export const newsConstants = {
    GET_ALL_NEWS_REQUEST: 'GET_ALL_NEWS_REQUEST',
    GET_ALL_NEWS_SUCCESS: 'GET_ALL_NEWS_SUCCESS',
    GET_ALL_NEWS_FAILURE: 'GET_ALL_NEWS_FAILURE',
    GET_SINGLE_NEWS_REQUEST: 'GET_SINGLE_NEWS_REQUEST',
    GET_SINGLE_NEWS_SUCCESS: 'GET_SINGLE_NEWS_SUCCESS',
    GET_SINGLE_NEWS_FAILURE: 'GET_SINGLE_NEWS_FAILURE',
    GET_CATEGORISED_NEWS_REQUEST: 'GET_CATEGORISED_NEWS_REQUEST',
    GET_CATEGORISED_NEWS_SUCCESS: 'GET_CATEGORISED_NEWS_SUCCESS',
    GET_CATEGORISED_NEWS_FAILURE: 'GET_CATEGORISED_NEWS_FAILURE',

}